# SPDX-FileCopyrightText: 2026 first-uninteresting-username
#
# SPDX-License-Identifier: GPL-3.0-or-later

[project]
site_name = "NixOS Config"
site_url = "https://first-uninteresting-username.github.io/NixOS-config/"
repo_url = "https://github.com/first-uninteresting-username/NixOS-config"

[project.theme]
features = [
  "content.code.copy",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
